/* Subtraction of Two Pointers :
							The subtraction of two pointers is possible only when 
					they have the same data type. The result is generated by 
					calculating the difference between the addresses of the two 
					pointers and calculating how many bits of data it is according
					to the pointer data type. 
					
	The subtraction of two pointers gives the increments between the two pointers. 

For Example: 
            Two integer pointers say ptr1(address:1000) and ptr2(address:1016) 
			are subtracted. The difference between address is 16 bytes. 
			Since the size of int is 2 bytes, therefore the increment between
			 ptr1 and ptr2 is given by (16/2) = 8.
			 
   Address2 - Address1 = (Subtraction of two addresses)/size of data type which pointer points 
*/

#include<stdio.h>
  
void main ()  
{  
    int i = 100;   
    int *p = &i;  
    int *temp;  
    temp = p; 
	
	printf("\np = %u",p);
	printf("\ntemp = %u",temp);
	  
    p = p + 3;  
    
    printf("\nPointer Subtraction: %d - %d = %d",p, temp, p-temp);  
}  
			 